### ISSUE TITLE
Unable to start BFLA learning

### ISSUE THREAD

**Issue by amccormi** [openclarity/apiclarity#339]
#### What happened:
In APIClarity v0.14.2, I tried to start BFLA learning for an API by hitting the start button, but the UI just refreshed to the screen with the start button again, and a generic error was reported at the top. In the APIClarity log, there was more useful information: "BFLA error: cannot enable traces: trace sampling is not enabled". So I enable trace sampling in the chart, and now it's working. I think either a descriptive error message should be shown in the UI (e.g. "Trace sampling is not enabled") or the BFLA tab shouldn't be shown if trace sampling is not enabled.

#### What you expected to happen:
Either a better error message should have been displayed, or the BFLA tab should be hidden if trace sampling is not enabled.

#### How to reproduce it (as minimally and precisely as possible):
Install APIClarity helm chart with trace sampling disabled (default). Try to start BFLA learning.

#### Are there any error messages in API Clarity logs?
"BFLA error: cannot enable traces: trace sampling is not enabled"

**Comment by aduminuc** [comment]
Solved in 0.14.4
