### ISSUE TITLE
no monitored traffic on the UI

### ISSUE THREAD

**Issue by jpgong** [openclarity/apiclarity#366]
APIclarity has been deployed correctly in the **sock-shop**  demo application, why is there no monitored traffic on the UI?

![image](https://github.com/openclarity/apiclarity/assets/27892657/338daa9e-8785-4be4-9801-7bccd9adc8a9)

![image](https://github.com/openclarity/apiclarity/assets/27892657/d09949a2-1014-4e1e-bcf4-54635dfae397)

kubectl logs -f apiclarity-apiclarity-7c96cc5c87-kd2md -n apiclarity，and reports warning:
`level=warning msg="External trace server not started because TLS is not enabled" func=github.com/openclarity/apiclarity/backend/pkg/backend.Run file="/build/backend/pkg/backend/backend.go:237"`

Is it because of this reason?
![image](https://github.com/openclarity/apiclarity/assets/27892657/1dab87d1-2c4c-4b6b-b092-c943feca7f5b)

**Comment by jpgong** [comment]
apiclarity can run normally, but the namespace traffic cannot be monitored in the **Istio Service Mesh** module. 
and, **Tap via a DaemonSet** module also can not monitor normal traffic, and error reports as follow in taper pod:
![image](https://github.com/openclarity/apiclarity/assets/27892657/bf056cd9-ce5b-467e-b8a9-2b25a0526ce3)

**Comment by amanhigh** [comment]
Even i am not clear how to enable Capture. Istio is already deployment but no Traffic. Is there any further guide on this ?
