### ISSUE TITLE
Color coding HTTP Verbs

### ISSUE THREAD

**Issue by jbogarin** [openclarity/apiclarity#46]
I saw a demo of the solution today and thought that a good idea would be to color code the HTTP verbs similar to what swagger UI supports.

I am talking about this interface:

<img width="476" alt="Screen Shot 2021-10-08 at 10 17 32" src="https://user-images.githubusercontent.com/4792616/136593224-281fc0f2-87ad-400f-b68d-a04e8899e391.png">

And using this:

![swagger_ui](https://user-images.githubusercontent.com/4792616/136593326-827fa57d-9de2-4af1-ae5d-ea2121273f63.png)

I think that from a UI/UX perspective, it makes it easier to consume.

**Comment by akpsgit** [comment]
Thank a lot for the suggestion! Great Idea. Will be added.

**Comment by akpsgit** [comment]
@jbogarin it was now handled in #133. Thanks again!
