### ISSUE TITLE
"helm uninstall apiclarity" does not clean pv and pvc resources

### ISSUE THREAD

**Issue by fishkerez** [openclarity/apiclarity#91]
When trying to uninstall APIClarity using helm, the PersistentVolume and PersistentVolumeClaim resources are not destroyed.
This causing the next installation to have already an existing data from previous installation.

Need to add to the README the correct way to uninstall APIClarity (meaning delete the pv as well)

**Comment by jadiaconu** [comment]
Hello everyone,
It seems that PVCs related to StatefulSets are not removed by helm.
Shall we add in the Readme an instruction to clean the PVCs (same for Kubeclarity) ?

`kubectl delete pvc -l  app.kubernetes.io/instance=apiclarity -n apiclarity`

**Comment by akpsgit** [comment]
Would be helpful :)
should we create a new "Uninstall/Cleanup" section (after K8s installation instructions?) with the helm uninstall and pvc deletion commands?

**Comment by FrimIdan** [comment]
s
